### ISSUE TITLE
OnBoarding 수정 필요.

### ISSUE THREAD

**Issue by Zi-Yun** [Carrierr/TipTap_Android#234]
1. OnBoarding에 사용되는 Adapter를 개별 클래스로 분류.
2. 태블릿 등에서 OnBoarding 이미지가 잘 보이도록 레이아웃 수정 필요.

**Comment by Jasonarea** [comment]
OnBoarding에서 수정하기 / 다음으로 버튼이 원활하게 작동이 안되는 오류 수정이 필요합니다!

**Comment by Zi-Yun** [comment]
#243 resolve
